shared:
  image: centos:centos7

jobs:
  blocked:
    annotations:
      screwdriver.cd/blockedBySameJob: false
      screwdriver.cd/blockedBySameJobWaitTime: 1
    requires: [ ~commit ]
    steps:
      - wait: sleep 600
